### ISSUE TITLE
OpenSwathWorkflow error 

### ISSUE THREAD

**Issue by Matthias313** [OpenSWATH/documentation#21]
Hi 

I tried to run OpenSwathWorkflow on a bunch of DIA files (in mzML format) using a pqp library and an iRT.tsv file.

I am using OSW from the OMS 2.5 release.

For 19/20 file OSW went through producing functional .osw files.

However for one of the input files i received the following error and OSW crashed.

Loaded 18738 proteins, 216044 compounds with 1296264 transitions.
Loading mzML file in/MST132_raw.mzML using readoptions cache
Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 52 SWATH windows and in total 2519 MS1 spectra
Determined there to be 52 SWATH windows and in total 2519 MS1 spectra
Will load iRT transitions and try to find iRT peptides
Warning: Found multiple peptide sequences for peptide label group light. This is most likely an error and to fix this, a new peptide label group will be inferred - to override this decision, please use the override_group_label_check parameter.
Will analyse 20 peptides with a total of 100 transitions 
# mz regression parameters: Y = -1.23697 + -0.00131831 X + 0 X^2
 sum residual sq ppm before 124.966 / after 53.8444
Will analyze 1296264 transitions in total.
Thread 0_0 will analyze 1959 compounds and 11754 transitions from SWATH 1 (batch 0 out of 1)
Thread 0_0 will analyze 1959 compounds and 11754 transitions from SWATH 1 (batch 1 out of 1)
Thread 0_0 will analyze 2212 compounds and 13272 transitions from SWATH 2 (batch 0 out of 2)
Thread 0_0 will analyze 2212 compounds and 13272 transitions from SWATH 2 (batch 1 out of 2)
Thread 0_0 will analyze 2212 compounds and 13272 transitions from SWATH 2 (batch 2 out of 2)
Thread 0_0 will analyze 2508 compounds and 15048 transitions from SWATH 3 (batch 0 out of 2)
Thread 0_0 will analyze 2508 compounds and 15048 transitions from SWATH 3 (batch 1 out of 2)
Thread 0_0 will analyze 2508 compounds and 15048 transitions from SWATH 3 (batch 2 out of 2)
WARNING in SignalToNoiseEstimatorMedian: 100% of all windows were sparse. You should consider increasing 'win_len' or decreasing 'min_required_elements'
Thread 0_0 will analyze 2695 compounds and 16170 transitions from SWATH 4 (batch 0 out of 2)
Thread 0_0 will analyze 2695 compounds and 16170 transitions from SWATH 4 (batch 1 out of 2)
Thread 0_0 will analyze 2695 compounds and 16170 transitions from SWATH 4 (batch 2 out of 2)
Thread 0_0 will analyze 2972 compounds and 17832 transitions from SWATH 5 (batch 0 out of 2)
Thread 0_0 will analyze 2972 compounds and 17832 transitions from SWATH 5 (batch 1 out of 2)
Thread 0_0 will analyze 2972 compounds and 17832 transitions from SWATH 5 (batch 2 out of 2)
Thread 0_0 will analyze 3322 compounds and 19932 transitions from SWATH 6 (batch 0 out of 3)
Thread 0_0 will analyze 3322 compounds and 19932 transitions from SWATH 6 (batch 1 out of 3)
Thread 0_0 will analyze 3322 compounds and 19932 transitions from SWATH 6 (batch 2 out of 3)

---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type IllegalArgument occured in line 112, function static void OpenMS::SqliteConnector::executeStatement(sqlite3*, const OpenMS::String&) of /opt/conda/conda-bld/openms-meta_1599077223540/work/src/openms/source/FORMAT/SqliteConnector.cpp
error message: no such column: inf
---------------------------------------------------

Any idea what could have happened here?

**Comment by bgruening** [comment]
I this fixed in the OpenMS 2.6 releases?

**Comment by Matthias313** [comment]
Noo I still get the same error.

Cmd window looks like the following:

Read chromatogram while reading SWATH files, did not expect that!
 - Warning: Detected 1 empty chromatograms. Will skip them!
 - Warning: Detected 1 empty chromatograms. Will skip them!
MRMRTNormalizer::computeBinnedCoverage : computed bin was too large (10), setting it to the maximum of 9
Error message after sqlite3_exec
Prepared statement INSERT INTO FEATURE (ID, RUN_ID, PRECURSOR_ID, EXP_RT, EXP_IM, NORM_RT, DELTA_RT, LEFT_WIDTH, RIGHT_WIDTH) VALUES (270467672082338228, 4974683169571601258, 44777, 1766.93, null, -26.0215, 60.4247, 1749.5377197265625, 1782.4119873046875); INSERT INTO FEATURE_MS1 (FEATURE_ID, AREA_INTENSITY, APEX_INTENSITY,  VAR_MASSDEV_SCORE, VAR_IM_MS1_DELTA_SCORE,  VAR_MI_SCORE, VAR_MI_CONTRAST_SCORE, VAR_MI_COMBINED_SCORE, VAR_ISOTOPE_CORRELATION_SCORE,  VAR_ISOTOPE_OVERLAP_SCORE, VAR_XCORR_COELUTION, VAR_XCORR_COELUTION_CONTRAST,  VAR_XCORR_COELUTION_COMBINED, VAR_XCORR_SHAPE, VAR_XCORR_SHAPE_CONTRAST, VAR_XCORR_SHAPE_COMBINED ) VALUES (270467672082338228, 8.628725781249999e04, 7.458024360119374e04, 53.162246164553984, null, 0.086585661745722, 0.036077359060718, 0.050015796096965, -0.631571907388784, 2.979715058988063, 13.378505426185217, 12.299659828522117, 12.770498036883094, 0.1, 0.015469123785457, 0.043113799470018); INSERT INTO FEATURE_PRECURSOR (FEATURE_ID, ISOTOPE, AREA_INTENSITY, APEX_INTENSITY) VALUES (270467672082338228, 0, 86287.3, 7.458024360119374e04); INSERT INTO FEATURE_MS2 (FEATURE_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI, VAR_BSERIES_SCORE, VAR_DOTPROD_SCORE, VAR_INTENSITY_SCORE, VAR_ISOTOPE_CORRELATION_SCORE, VAR_ISOTOPE_OVERLAP_SCORE, VAR_LIBRARY_CORR,  VAR_LIBRARY_DOTPROD, VAR_LIBRARY_MANHATTAN, VAR_LIBRARY_RMSD, VAR_LIBRARY_ROOTMEANSQUARE, VAR_LIBRARY_SANGLE, VAR_LOG_SN_SCORE, VAR_MANHATTAN_SCORE, VAR_MASSDEV_SCORE, VAR_MASSDEV_SCORE_WEIGHTED, VAR_MI_SCORE, VAR_MI_WEIGHTED_SCORE, VAR_MI_RATIO_SCORE, VAR_NORM_RT_SCORE, VAR_XCORR_COELUTION,VAR_XCORR_COELUTION_WEIGHTED, VAR_XCORR_SHAPE, VAR_XCORR_SHAPE_WEIGHTED, VAR_YSERIES_SCORE, VAR_ELUTION_MODEL_FIT_SCORE, VAR_IM_XCORR_SHAPE, VAR_IM_XCORR_COELUTION, VAR_IM_DELTA_SCORE, VAR_SONAR_LAG, VAR_SONAR_SHAPE, VAR_SONAR_LOG_SN, VAR_SONAR_LOG_DIFF, VAR_SONAR_LOG_TREND, VAR_SONAR_RSQ ) VALUES (270467672082338228, 3.44141e+06, inf, 7.154459375e05, null, 0.0, 0.412511056016711, 0.0, 0.547154490411711, 0.0, -0.094632044681477, 0.389249472080761, 1.673207435425363, 0.282828282828283, 0.386091209163968, 1.222818886781381, 2.868137484001519, 1.389872735971249, 6.473401267608715, 4.989508062322411, null, null, null, 0.018431993225046, 12.876587268786393, 10.747474747474749, 0.047619047619048, 0.022956841138659, 3.0, null, null, null, null, null, null, null, null, null, null); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268666, 0, 4.688313697265625e06, 0.0, NULL); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268662, 3.44141e+06, 7.694264015625e06, 7.154459375e05, NULL); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268663, 0, inf, 0.0, NULL); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268667, 0, 1.1026890625e05, 0.0, NULL); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268664, 0, 0.0, 0.0, NULL); INSERT INTO FEATURE_TRANSITION (FEATURE_ID, TRANSITION_ID, AREA_INTENSITY, TOTAL_AREA_INTENSITY, APEX_INTENSITY, TOTAL_MI) VALUES (270467672082338228, 268665, 0, 0.0, 0.0, NULL); 
/data/dnb03/galaxy_db/job_working_directory/011/782/11782543/tool_script.sh: line 73: 3166367 Aborted                 OpenSwathWorkflow -ini OpenSwathWorkflow.ctd -in 'in/MST132_mzML.mzML' -tr 'tr/HEK_Ecoli_unique_3_EG.pqp' -tr_irt 'tr_irt/iRTassays_tsv.tsv' -out_osw 'out_osw/output.osw'
